name: Build and Deploy
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: ghpages-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: QuinnBast/QuinnBast.github.io
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: cd src && yarn && yarn build
        BUILD_DIR: src/.vuepress/dist